use_frameworks!

platform :ios, '11.0'

target 'SwiftRouter_Example' do
  pod 'SwiftRouter', :path => '../'

  target 'SwiftRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
